config/routes.rb
Rails.application.routes.draw do
  resources :wikis

  devise_for :users

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  after_initialize { self.role ||= :standard }
  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :about]

  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>



</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Keep it factual.</li>
      <li>Do not make false edits.</li>
      <li>Politics and personal opinions are not welcome.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |w| %>
      <div class="form-group">
        <%= w.label :title %>
        <%= w.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= w.label :body %>
        <%= w.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= w.label :private, class: 'checkbox' do %>
          <%= w.check_box :private %> Private wiki?
        <% end %>
      </div>
      <div class="form-group">
        <%= w.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis &nbsp; <%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn btn-success' %></h1>
 <% @wikis.each do |wiki| %>
 <div class="media">
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to wiki.title, wiki %>
     </h4>
   </div>
 </div>
 <% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>The Way of the Wiki</p>
    <ul>
      <li>Keep it factual.</li>
      <li>Do not make false edits.</li>
      <li>Politics and personal opinions are not welcome.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |w| %>
      <div class="form-group">
        <%= w.label :title %>
        <%= w.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= w.label :body %>
        <%= w.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= w.label :private, class: 'checkbox' do %>
          <%= w.check_box :private %> Private wiki?
        <% end %>
      </div>
      <div class="form-group">
        <%= w.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @wiki.body %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>